"""baseline schema — all tables from the SQLAlchemy models

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-26

ponytail: the baseline builds the whole schema straight from ``Base.metadata`` instead of
hand-listing 40+ ``op.create_table`` calls — it cannot drift from the models. Future schema
changes get their own autogenerated, reviewable migrations stacked on top of this one.
"""

from __future__ import annotations

import app.db.models  # noqa: F401  registers every model on Base.metadata
from alembic import op
from app.db.base import Base

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
