"""WS10.1 — dpdp_rights_request table (+RLS, §0.8) and the legal_acceptance doc_type widen.

Two schema paths, handled the way 0004/0005 established:

* **Postgres (production, tenant_core)** — the SQL is INLINED as a verbatim snapshot of
  ``infra/db/multitenant/008_dpdp.sql`` (a migration's content must be immutable; the .sql file
  stays the reviewable/red-team source and the RLS-coverage-gate input; any later change is a
  NEW revision). Creates the tenant table with RLS + policy in the SAME revision, and widens
  the ``legal_acceptance.doc_type`` CHECK to admit ``dpdp_notice``.
* **SQLite (dev/test)** — the 0005 existence-guard pattern: ``0001_baseline`` is
  ``Base.metadata.create_all`` from the LIVE models, so a fresh database already has the table
  when this revision runs; a pre-existing dev database migrated before the model change still
  needs the CREATE. SQLite doc_type has no CHECK to widen (0004 was a Postgres-only replay).

Revision ID: 0010_dpdp_rights
Revises: 0009_itc_ims_action
Create Date: 2026-07-23
"""

# ruff: noqa: E501 — the SQL below is a verbatim snapshot; reflowing it would break the
# byte-for-byte correspondence with infra/db/multitenant/008_dpdp.sql that makes it reviewable.
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0010_dpdp_rights"
down_revision = "0009_itc_ims_action"
branch_labels = None
depends_on = None

TENANT_SCHEMA = "tenant_core"


# ---- snapshot of infra/db/multitenant/008_dpdp.sql ---------------------------------------
_008_SQL = """
-- MMX-1.0 §WS10.1 — DPDP rights workflow: dpdp_rights_request + widen legal_acceptance's
-- doc_type CHECK to admit the versioned DPDP notice.
--
-- TENANT-SCOPED. A rights request is a fact about one customer org's data-principal, so the
-- row carries org_id and gets the standard RLS treatment every tenant table in 001–007 gets:
-- policy keyed on app_current_org() (the session GUC set from the VERIFIED JWT claim — never a
-- request body, §0.8). No org bound -> NULL -> the policy matches zero rows (fail closed).
--
-- The app role gets UPDATE (status open->held->completed, closed_date) but NOT DELETE: a
-- rights request is compliance evidence; its lifecycle events are additionally sealed onto the
-- append-only audit chain (the processing log), which is never pruned (>=1y retention by
-- construction).

CREATE TABLE dpdp_rights_request (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id                uuid NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  requester             text NOT NULL,
  request_type          text NOT NULL CHECK (request_type IN ('access', 'correction', 'erasure')),
  details               text,
  received_date         text NOT NULL,
  due_date              text NOT NULL,
  status                text NOT NULL CHECK (status IN ('open', 'held', 'completed')),
  hold_basis            text,
  calendar_deadline_id  bigint,
  closed_date           text
);
CREATE INDEX dpdp_rights_request_org ON dpdp_rights_request(org_id, status);

ALTER TABLE dpdp_rights_request ENABLE ROW LEVEL SECURITY;
ALTER TABLE dpdp_rights_request FORCE  ROW LEVEL SECURITY;
CREATE POLICY dpdp_rights_request_tenant ON dpdp_rights_request
  USING (org_id = app_current_org()) WITH CHECK (org_id = app_current_org());

GRANT SELECT, INSERT, UPDATE ON dpdp_rights_request TO maisha_app;

-- legal_acceptance (004) constrained doc_type to the WS10.4 trio; the WS10.1 DPDP notice is a
-- fourth versioned document using the SAME acceptance mechanics. Postgres auto-named the
-- inline CHECK <table>_<column>_check.
ALTER TABLE legal_acceptance DROP CONSTRAINT IF EXISTS legal_acceptance_doc_type_check;
ALTER TABLE legal_acceptance ADD CONSTRAINT legal_acceptance_doc_type_check
  CHECK (doc_type IN ('tos', 'privacy', 'dpa', 'dpdp_notice'));
"""


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(f"SET search_path TO {TENANT_SCHEMA}, public")
        op.execute(_008_SQL)
        op.execute("SET search_path TO public")
        return
    # SQLite (dev/test): 0005 existence-guard — fresh DBs already have the table via the
    # 0001 create_all baseline; only an older migrated dev DB needs the CREATE.
    if "dpdp_rights_request" not in sa.inspect(bind).get_table_names():
        from app.db.models.legal import DpdpRightsRequest

        DpdpRightsRequest.__table__.create(bind)


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(f"DROP TABLE IF EXISTS {TENANT_SCHEMA}.dpdp_rights_request")
        return
    op.drop_table("dpdp_rights_request")
