import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1782926120273 implements MigrationInterface {
    name = 'InitSchema1782926120273'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "company" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "cin" text, "pan" character varying NOT NULL, "gstin" text, "incorporation_date" text, "financial_year_end" character varying NOT NULL DEFAULT '03-31', "msme_registration" text, "dpiit_recognition" text, "sector" text, "address" text, "state" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_693d80b3eb1a04c0efc99f3ae4a" UNIQUE ("cin"), CONSTRAINT "UQ_f2fb761ff9796be207809235707" UNIQUE ("pan"), CONSTRAINT "UQ_67fd0f0229f9e593fee3fdd2085" UNIQUE ("gstin"), CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "name" text, "role" character varying NOT NULL DEFAULT 'founder', "expertise" character varying NOT NULL DEFAULT 'founder', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_log" ("id" SERIAL NOT NULL, "timestamp" character varying NOT NULL, "action" character varying NOT NULL, "domain" character varying NOT NULL, "user_id" character varying NOT NULL, "query" text, "intent_global" text, "intent_domain" text, "validation_status" text, "rules_version" character varying NOT NULL, "prev_hash" text, "this_hash" text, CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "llm_trace" ("id" SERIAL NOT NULL, "timestamp" character varying NOT NULL, "domain" character varying NOT NULL, "audit_hash" text, "model_label" character varying NOT NULL, "input_sha256" character varying NOT NULL, "claim_sha256" text, "attempts" integer NOT NULL DEFAULT '1', "verified" integer NOT NULL DEFAULT '0', "requires_approval" integer NOT NULL DEFAULT '0', "latency_ms" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_3a07bd11a56948d151c62380887" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "metric_snapshot" ("id" SERIAL NOT NULL, "captured_at" character varying NOT NULL, "domain" character varying NOT NULL, "metric" character varying NOT NULL, "value" double precision NOT NULL, CONSTRAINT "PK_f7aaa9173a3391312cc24ecde07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "decision" ("id" SERIAL NOT NULL, "timestamp" character varying NOT NULL, "domain" character varying NOT NULL, "decision" character varying NOT NULL, "state_hash" character varying NOT NULL, "audit_hash" text, "user_id" character varying NOT NULL, CONSTRAINT "PK_fa4cbd6abf1215054f13c27df5a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "compliance_calendar" ("id" SERIAL NOT NULL, "domain" character varying NOT NULL, "form_name" character varying NOT NULL, "due_date" character varying NOT NULL, "filing_period" text, "status" character varying NOT NULL DEFAULT 'pending', "filed_date" text, "acknowledgement" text, "penalty_amount" bigint NOT NULL DEFAULT '0', "reminder_sent" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_375e44ca623e3839afa7fff6ec5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rules_registry" ("id" SERIAL NOT NULL, "version" character varying NOT NULL, "domain" character varying NOT NULL, "rule_id" character varying NOT NULL, "description" text NOT NULL, "statute" text, "section" text, "condition_logic" text, "severity" character varying NOT NULL DEFAULT 'warning', "active" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b4b80d598118bee96bf9e92be6b" UNIQUE ("rule_id"), CONSTRAINT "PK_dd5babeef5f22c0be7f38c6daee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bank_accounts" ("id" SERIAL NOT NULL, "bank_name" character varying NOT NULL, "account_number" character varying NOT NULL, "ifsc" character varying NOT NULL, "account_type" text, "opening_balance" bigint NOT NULL DEFAULT '0', "current_balance" bigint NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'INR', "is_primary" integer NOT NULL DEFAULT '0', "last_sync" text, CONSTRAINT "PK_c872de764f2038224a013ff25ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bank_transactions" ("id" SERIAL NOT NULL, "account_id" integer NOT NULL, "txn_date" character varying NOT NULL, "description" text, "reference" text, "debit" bigint NOT NULL DEFAULT '0', "credit" bigint NOT NULL DEFAULT '0', "balance" bigint, "category" text, "matched_invoice_id" integer, "matched_vendor_id" integer, "is_reconciled" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_123cc87304eefb2c497b4acdd10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fixed_deposits" ("id" SERIAL NOT NULL, "bank_account_id" integer, "fd_number" character varying NOT NULL, "principal" bigint NOT NULL, "interest_rate" double precision NOT NULL, "start_date" character varying NOT NULL, "maturity_date" character varying NOT NULL, "maturity_amount" bigint, "tds_deducted" bigint NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'active', CONSTRAINT "PK_7ca9fbaf78f710dd26ab7d2a1df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" character varying NOT NULL, "file_name" character varying NOT NULL, "file_path" character varying NOT NULL, "doc_type" character varying NOT NULL, "domain" text, "entity_id" text, "ocr_text" text, "upload_date" character varying NOT NULL, "retention_until" text, "sha256" character varying NOT NULL, "tags" text, "uploaded_by" text, "version" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds_returns" ("id" SERIAL NOT NULL, "return_type" character varying NOT NULL, "quarter" character varying NOT NULL, "due_date" character varying NOT NULL, "filed_date" text, "status" character varying NOT NULL DEFAULT 'pending', "total_deducted" bigint NOT NULL DEFAULT '0', "total_deposited" bigint NOT NULL DEFAULT '0', "late_filing_fee" bigint NOT NULL DEFAULT '0', "json_file_path" text, CONSTRAINT "PK_69cc190f255e13fb6098272fe63" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tds_entries" ("id" SERIAL NOT NULL, "tds_return_id" integer, "deductee_name" character varying NOT NULL, "deductee_pan" text, "section" character varying NOT NULL, "payment_date" character varying NOT NULL, "payment_amount" bigint NOT NULL, "tds_rate" double precision NOT NULL DEFAULT '0', "tds_amount" bigint NOT NULL, "surcharge" bigint NOT NULL DEFAULT '0', "cess" bigint NOT NULL DEFAULT '0', "total_tds" bigint NOT NULL, "deposit_date" text, "challan_number" text, "bsr_code" text, CONSTRAINT "PK_384cdd69b8c15f55ecee70b178f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "advance_tax" ("id" SERIAL NOT NULL, "fy" character varying NOT NULL, "installment" character varying NOT NULL, "due_date" character varying NOT NULL, "paid_date" text, "amount" bigint NOT NULL, "challan_number" text, "bsr_code" text, "status" character varying NOT NULL DEFAULT 'pending', CONSTRAINT "PK_d8de3a8aeea0b33d4d43b7fd132" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "pan" text, "gstin" text, "email" text, "phone" text, "address" text, "state" text, "payment_terms" integer NOT NULL DEFAULT '30', "tds_applicable" integer NOT NULL DEFAULT '0', "tds_section" text, "tds_rate" double precision NOT NULL DEFAULT '0', "created_at" text, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" SERIAL NOT NULL, "invoice_number" character varying NOT NULL, "customer_id" integer NOT NULL, "invoice_date" character varying NOT NULL, "due_date" character varying NOT NULL, "subtotal" bigint NOT NULL, "gst_rate" double precision NOT NULL DEFAULT '0', "igst_amount" bigint NOT NULL DEFAULT '0', "cgst_amount" bigint NOT NULL DEFAULT '0', "sgst_amount" bigint NOT NULL DEFAULT '0', "total_amount" bigint NOT NULL, "tds_amount" bigint NOT NULL DEFAULT '0', "net_receivable" bigint NOT NULL, "irn" text, "qr_code_path" text, "status" character varying NOT NULL DEFAULT 'draft', "paid_date" text, "paid_amount" bigint NOT NULL DEFAULT '0', CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_items" ("id" SERIAL NOT NULL, "invoice_id" integer NOT NULL, "description" character varying NOT NULL, "hsn_code" text, "quantity" integer NOT NULL DEFAULT '1', "rate" bigint NOT NULL, "amount" bigint NOT NULL, CONSTRAINT "PK_53b99f9e0e2945e69de1a12b75a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "credit_notes" ("id" SERIAL NOT NULL, "credit_note_number" character varying NOT NULL, "invoice_id" integer NOT NULL, "issue_date" character varying NOT NULL, "reason" text, "amount" bigint NOT NULL, "gst_adjustment" bigint NOT NULL DEFAULT '0', CONSTRAINT "UQ_a7078fae5ed0ec6e160f4319331" UNIQUE ("credit_note_number"), CONSTRAINT "PK_4933888a20b5469e119ad74b9e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employees" ("id" SERIAL NOT NULL, "employee_code" character varying NOT NULL, "name" character varying NOT NULL, "email" text, "phone" text, "pan" text, "uan" text, "esi_ip_number" text, "date_of_joining" character varying NOT NULL, "date_of_exit" text, "status" character varying NOT NULL DEFAULT 'active', "state" text, "bank_account" text, "ifsc" text, CONSTRAINT "UQ_56162b5f24af743a154680684f5" UNIQUE ("employee_code"), CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "salary_structures" ("id" SERIAL NOT NULL, "employee_id" integer NOT NULL, "effective_from" character varying NOT NULL, "basic" bigint NOT NULL, "hra" bigint NOT NULL, "lta" bigint NOT NULL DEFAULT '0', "special_allowance" bigint NOT NULL DEFAULT '0', "employer_pf" bigint NOT NULL, "employer_esi" bigint NOT NULL DEFAULT '0', "employee_pf" bigint NOT NULL, "employee_esi" bigint NOT NULL DEFAULT '0', "professional_tax" bigint NOT NULL DEFAULT '0', "tds_monthly" bigint NOT NULL DEFAULT '0', "gross_salary" bigint NOT NULL, "net_salary" bigint NOT NULL, "ctc" bigint NOT NULL, CONSTRAINT "PK_1800f745fd1ebe08981cd422acd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payroll_runs" ("id" SERIAL NOT NULL, "month_year" character varying NOT NULL, "run_date" character varying NOT NULL, "total_gross" bigint NOT NULL DEFAULT '0', "total_deductions" bigint NOT NULL DEFAULT '0', "total_net" bigint NOT NULL DEFAULT '0', "total_pf_employer" bigint NOT NULL DEFAULT '0', "total_esi_employer" bigint NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'draft', "ecr_generated" integer NOT NULL DEFAULT '0', "ecr_file_path" text, CONSTRAINT "PK_6049f42c972640c0eb99ba8035e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payroll_entries" ("id" SERIAL NOT NULL, "payroll_run_id" integer NOT NULL, "employee_id" integer NOT NULL, "gross" bigint NOT NULL, "basic" bigint NOT NULL, "hra" bigint NOT NULL, "lta" bigint NOT NULL DEFAULT '0', "special_allowance" bigint NOT NULL DEFAULT '0', "employee_pf" bigint NOT NULL, "employee_esi" bigint NOT NULL DEFAULT '0', "professional_tax" bigint NOT NULL DEFAULT '0', "tds" bigint NOT NULL DEFAULT '0', "other_deductions" bigint NOT NULL DEFAULT '0', "employer_pf" bigint NOT NULL DEFAULT '0', "employer_esi" bigint NOT NULL DEFAULT '0', "net_pay" bigint NOT NULL, CONSTRAINT "PK_749b8c91480734ee1e616d4456d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "esop_grants" ("id" SERIAL NOT NULL, "employee_id" integer NOT NULL, "grant_date" character varying NOT NULL, "vesting_start_date" character varying NOT NULL, "cliff_months" integer NOT NULL DEFAULT '12', "vesting_period_months" integer NOT NULL DEFAULT '48', "total_options" integer NOT NULL, "exercise_price" bigint NOT NULL, "vested_options" integer NOT NULL DEFAULT '0', "exercised_options" integer NOT NULL DEFAULT '0', "forfeited_options" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_daeb8075b64ed2f11dae2561420" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vendors" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "pan" text, "gstin" text, "msme_status" integer NOT NULL DEFAULT '0', "msme_type" text, "bank_account" text, "ifsc" text, "payment_terms" integer NOT NULL DEFAULT '30', "tds_section" text, "payee_type" character varying NOT NULL DEFAULT 'company', CONSTRAINT "PK_9c956c9797edfae5c6ddacc4e6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" SERIAL NOT NULL, "po_number" character varying NOT NULL, "vendor_id" integer NOT NULL, "po_date" character varying NOT NULL, "delivery_date" text, "total_amount" bigint NOT NULL, "received_amount" bigint NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'open', CONSTRAINT "UQ_74065a5d2b8c4c14b8b8fcf0159" UNIQUE ("po_number"), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bills" ("id" SERIAL NOT NULL, "bill_number" character varying NOT NULL, "vendor_id" integer NOT NULL, "po_id" integer, "bill_date" character varying NOT NULL, "due_date" character varying NOT NULL, "subtotal" bigint NOT NULL, "gst_amount" bigint NOT NULL DEFAULT '0', "igst_amount" bigint NOT NULL DEFAULT '0', "cgst_amount" bigint NOT NULL DEFAULT '0', "sgst_amount" bigint NOT NULL DEFAULT '0', "tds_amount" bigint NOT NULL DEFAULT '0', "total_amount" bigint NOT NULL, "itc_eligible" integer NOT NULL DEFAULT '1', "status" character varying NOT NULL DEFAULT 'open', "paid_date" text, "paid_amount" bigint NOT NULL DEFAULT '0', CONSTRAINT "PK_a56215dfcb525755ec832cc80b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chart_of_accounts" ("id" SERIAL NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "account_type" character varying NOT NULL, "sub_type" text, "parent_id" integer, "is_bank_account" integer NOT NULL DEFAULT '0', "is_cash_account" integer NOT NULL DEFAULT '0', "opening_balance" bigint NOT NULL DEFAULT '0', CONSTRAINT "UQ_e739f9fb242a95d501aedde46c8" UNIQUE ("code"), CONSTRAINT "PK_467c08a2efc78393c647da32bac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "journal_entries" ("id" SERIAL NOT NULL, "entry_date" character varying NOT NULL, "reference" text, "description" character varying NOT NULL, "source" text, "total_debit" bigint NOT NULL, "total_credit" bigint NOT NULL, "is_auto_generated" integer NOT NULL DEFAULT '0', "created_at" text, CONSTRAINT "PK_a70368e64230434457c8d007ab3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "journal_lines" ("id" SERIAL NOT NULL, "journal_entry_id" integer NOT NULL, "account_id" integer NOT NULL, "debit" bigint NOT NULL DEFAULT '0', "credit" bigint NOT NULL DEFAULT '0', "description" text, CONSTRAINT "PK_70cba2da4588cee8921f73ef136" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fixed_assets" ("id" SERIAL NOT NULL, "asset_name" character varying NOT NULL, "asset_code" text, "purchase_date" character varying NOT NULL, "purchase_cost" bigint NOT NULL, "salvage_value" bigint NOT NULL DEFAULT '0', "useful_life_years" integer NOT NULL, "depreciation_method" character varying NOT NULL DEFAULT 'wdv', "depreciation_rate" double precision NOT NULL DEFAULT '0', "accumulated_depreciation" bigint NOT NULL DEFAULT '0', "wdv" bigint NOT NULL, "disposal_date" text, "disposal_amount" bigint, "status" character varying NOT NULL DEFAULT 'active', CONSTRAINT "PK_901984c25ddf1dcf11f1c7a70d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gst_returns" ("id" SERIAL NOT NULL, "return_type" character varying NOT NULL, "filing_period" character varying NOT NULL, "due_date" character varying NOT NULL, "filed_date" text, "status" character varying NOT NULL DEFAULT 'pending', "json_file_path" text, "acknowledgement" text, "tax_payable" bigint NOT NULL DEFAULT '0', "tax_paid" bigint NOT NULL DEFAULT '0', "late_fee" bigint NOT NULL DEFAULT '0', "interest" bigint NOT NULL DEFAULT '0', CONSTRAINT "PK_08a93f63d9550bb078eebc5816b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "itc_register" ("id" SERIAL NOT NULL, "invoice_id" integer, "bill_id" integer, "gstin_supplier" character varying NOT NULL, "invoice_number" character varying NOT NULL, "invoice_date" character varying NOT NULL, "taxable_value" bigint NOT NULL, "igst" bigint NOT NULL DEFAULT '0', "cgst" bigint NOT NULL DEFAULT '0', "sgst" bigint NOT NULL DEFAULT '0', "total_tax" bigint NOT NULL, "eligible_itc" integer NOT NULL DEFAULT '1', "in_2b" integer NOT NULL DEFAULT '0', "claimed_in_return" text, CONSTRAINT "PK_c709d3b2681acdd3d9788a6848e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "budgets" ("id" SERIAL NOT NULL, "fy" character varying NOT NULL, "category" character varying NOT NULL, "sub_category" text, "jan" bigint NOT NULL DEFAULT '0', "feb" bigint NOT NULL DEFAULT '0', "mar" bigint NOT NULL DEFAULT '0', "apr" bigint NOT NULL DEFAULT '0', "may" bigint NOT NULL DEFAULT '0', "jun" bigint NOT NULL DEFAULT '0', "jul" bigint NOT NULL DEFAULT '0', "aug" bigint NOT NULL DEFAULT '0', "sep" bigint NOT NULL DEFAULT '0', "oct" bigint NOT NULL DEFAULT '0', "nov" bigint NOT NULL DEFAULT '0', "dec" bigint NOT NULL DEFAULT '0', "annual_total" bigint NOT NULL, CONSTRAINT "PK_9c8a51748f82387644b773da482" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "forecasts" ("id" SERIAL NOT NULL, "forecast_date" character varying NOT NULL, "horizon_months" integer NOT NULL DEFAULT '12', "scenario" character varying NOT NULL DEFAULT 'base', "revenue_forecast" bigint, "burn_forecast" bigint, "headcount_forecast" integer, "cash_forecast" bigint, "runway_forecast" real, "assumptions" text, CONSTRAINT "PK_caa4d5aec48032eb9d2ce8535f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "expense_claims" ("id" SERIAL NOT NULL, "employee_id" integer, "claim_date" character varying NOT NULL, "expense_date" character varying NOT NULL, "category" character varying NOT NULL, "amount" bigint NOT NULL, "gst_amount" bigint NOT NULL DEFAULT '0', "vendor_name" text, "description" text, "receipt_document_id" text, "over_policy" integer NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'submitted', "approved_by" text, "approved_date" text, "reimbursement_date" text, CONSTRAINT "PK_df3bf7ea3a3a31e39525a322ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shareholders" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "category" character varying NOT NULL, "pan" text, "email" text, "investment_date" text, "investment_amount" bigint NOT NULL DEFAULT '0', "share_class" text, "shares_held" integer NOT NULL DEFAULT '0', "share_premium" bigint NOT NULL DEFAULT '0', "pre_money_valuation" bigint, "post_money_valuation" bigint, "anti_dilution" text, "liquidation_preference" double precision, "board_seat" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_bbe6cd94b1b69fe6edb73f983a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "safe_notes" ("id" SERIAL NOT NULL, "investor_id" integer NOT NULL, "issue_date" character varying NOT NULL, "investment_amount" bigint NOT NULL, "valuation_cap" bigint, "discount_rate" double precision NOT NULL DEFAULT '0', "pro_rata_rights" integer NOT NULL DEFAULT '1', "conversion_trigger" text, "converted" integer NOT NULL DEFAULT '0', "conversion_date" text, "shares_issued" integer, CONSTRAINT "PK_321a971d284d0f5b711393f2560" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cap_table_snapshots" ("id" SERIAL NOT NULL, "snapshot_date" character varying NOT NULL, "total_shares" integer NOT NULL, "total_diluted_shares" integer NOT NULL, "esop_pool_shares" integer NOT NULL DEFAULT '0', "esop_pool_pct" double precision NOT NULL DEFAULT '0', "esop_board_approved" integer NOT NULL DEFAULT '1', "snapshot_json" character varying NOT NULL, CONSTRAINT "PK_b372d720fd5a363b1fef04e7c8a" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "cap_table_snapshots"`);
        await queryRunner.query(`DROP TABLE "safe_notes"`);
        await queryRunner.query(`DROP TABLE "shareholders"`);
        await queryRunner.query(`DROP TABLE "expense_claims"`);
        await queryRunner.query(`DROP TABLE "forecasts"`);
        await queryRunner.query(`DROP TABLE "budgets"`);
        await queryRunner.query(`DROP TABLE "itc_register"`);
        await queryRunner.query(`DROP TABLE "gst_returns"`);
        await queryRunner.query(`DROP TABLE "fixed_assets"`);
        await queryRunner.query(`DROP TABLE "journal_lines"`);
        await queryRunner.query(`DROP TABLE "journal_entries"`);
        await queryRunner.query(`DROP TABLE "chart_of_accounts"`);
        await queryRunner.query(`DROP TABLE "bills"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TABLE "vendors"`);
        await queryRunner.query(`DROP TABLE "esop_grants"`);
        await queryRunner.query(`DROP TABLE "payroll_entries"`);
        await queryRunner.query(`DROP TABLE "payroll_runs"`);
        await queryRunner.query(`DROP TABLE "salary_structures"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TABLE "credit_notes"`);
        await queryRunner.query(`DROP TABLE "invoice_items"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "advance_tax"`);
        await queryRunner.query(`DROP TABLE "tds_entries"`);
        await queryRunner.query(`DROP TABLE "tds_returns"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TABLE "fixed_deposits"`);
        await queryRunner.query(`DROP TABLE "bank_transactions"`);
        await queryRunner.query(`DROP TABLE "bank_accounts"`);
        await queryRunner.query(`DROP TABLE "rules_registry"`);
        await queryRunner.query(`DROP TABLE "compliance_calendar"`);
        await queryRunner.query(`DROP TABLE "decision"`);
        await queryRunner.query(`DROP TABLE "metric_snapshot"`);
        await queryRunner.query(`DROP TABLE "llm_trace"`);
        await queryRunner.query(`DROP TABLE "audit_log"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "company"`);
    }

}
