-- MMX-1.0 §WS10.1 — DPDP rights workflow: dpdp_rights_request + widen legal_acceptance's
-- doc_type CHECK to admit the versioned DPDP notice.
--
-- TENANT-SCOPED. A rights request is a fact about one customer org's data-principal, so the
-- row carries org_id and gets the standard RLS treatment every tenant table in 001–007 gets:
-- policy keyed on app_current_org() (the session GUC set from the VERIFIED JWT claim — never a
-- request body, §0.8). No org bound -> NULL -> the policy matches zero rows (fail closed).
--
-- The app role gets UPDATE (status open->held->completed, closed_date) but NOT DELETE: a
-- rights request is compliance evidence; its lifecycle events are additionally sealed onto the
-- append-only audit chain (the processing log), which is never pruned (>=1y retention by
-- construction).

CREATE TABLE dpdp_rights_request (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id                uuid NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  requester             text NOT NULL,
  request_type          text NOT NULL CHECK (request_type IN ('access', 'correction', 'erasure')),
  details               text,
  received_date         text NOT NULL,
  due_date              text NOT NULL,
  status                text NOT NULL CHECK (status IN ('open', 'held', 'completed')),
  hold_basis            text,
  calendar_deadline_id  bigint,
  closed_date           text
);
CREATE INDEX dpdp_rights_request_org ON dpdp_rights_request(org_id, status);

ALTER TABLE dpdp_rights_request ENABLE ROW LEVEL SECURITY;
ALTER TABLE dpdp_rights_request FORCE  ROW LEVEL SECURITY;
CREATE POLICY dpdp_rights_request_tenant ON dpdp_rights_request
  USING (org_id = app_current_org()) WITH CHECK (org_id = app_current_org());

GRANT SELECT, INSERT, UPDATE ON dpdp_rights_request TO maisha_app;

-- legal_acceptance (004) constrained doc_type to the WS10.4 trio; the WS10.1 DPDP notice is a
-- fourth versioned document using the SAME acceptance mechanics. Postgres auto-named the
-- inline CHECK <table>_<column>_check.
ALTER TABLE legal_acceptance DROP CONSTRAINT IF EXISTS legal_acceptance_doc_type_check;
ALTER TABLE legal_acceptance ADD CONSTRAINT legal_acceptance_doc_type_check
  CHECK (doc_type IN ('tos', 'privacy', 'dpa', 'dpdp_notice'));
